## AdoptOpenJDK 停止发布 OpenJDK 二进制，而 Eclipse Temurin 是它的延伸，提供更好的稳定性
FROM eclipse-temurin:8-jre
# author
MAINTAINER xgy

# 容器内创建目录
RUN mkdir -p /home/dts/receive
# 指定路径
WORKDIR /home/dts/receive
# 复制jar文件到路径
COPY ./jar/dts-receive-1.0.0.jar /home/dts/receive/dts-receive-1.0.0.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","dts-receive-1.0.0.jar"]