## AdoptOpenJDK 停止发布 OpenJDK 二进制，而 Eclipse Temurin 是它的延伸，提供更好的稳定性
FROM eclipse-temurin:8-jre
# author
MAINTAINER xgy

# 容器内创建目录
RUN mkdir -p /home/dts/all
# 指定路径
WORKDIR /home/dts/all
# 复制jar文件到路径
COPY ./jar/dts-all-biz-1.0.0.jar /home/dts/all/dts-all-biz-1.0.0.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","dts-all-biz-1.0.0.jar"]